// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get cancel => 'Cancel';

  @override
  String get ok => 'OK';

  @override
  String get send => 'Send';

  @override
  String get confirm => 'Confirm';

  @override
  String get delete => 'Delete';

  @override
  String get settings => 'Settings';

  @override
  String get skip => 'Skip';

  @override
  String get setupPageEnvelopeKeyHint =>
      'Paste the key envelope (contents of envelope-*.txt)';

  @override
  String get setupPageNeedPassphrase =>
      '⚠️ Set an access passphrase above first (your partner joins with it)';

  @override
  String get setupEnrollBoundNotice => 'New device bound to my private space';

  @override
  String get wizardStartTitle => 'Finding EINZ';

  @override
  String get wizardDetectTitle => 'Checking server status…';

  @override
  String get wizardDetectHint =>
      'We\'ll detect whether you\'re the first user (first device creates the space)';

  @override
  String get wizardDetectFailed =>
      'Cannot reach server — enter the address above and retry';

  @override
  String get wizardNameHint =>
      'This is your first device. Tell us what to call you (you can rename anytime).';

  @override
  String get wizardPeerNameHint =>
      'This is your partner (second user) — how should we call them? You can change it later.';

  @override
  String get wizardPeerNameHintInput => 'e.g. Steffi';

  @override
  String get wizardNameRequired => 'Please enter your name first';

  @override
  String get wizardPeerNameRequired => 'Please enter your partner\'s name';

  @override
  String get wizardNameHintInput => 'e.g. Lukas (optional, change later)';

  @override
  String get wizardIdentityHint => 'This space is limited to two people.';

  @override
  String get wizardIdentityCreator => 'First user (creator)';

  @override
  String get wizardIdentityPartner => 'Second user (partner)';

  @override
  String get wizardIdentityFirst =>
      '⚠️ Choose your identity first (creator or partner)';

  @override
  String get wizardInviteHint =>
      'Enter the one-time invite code from the creator (generated by /invite, valid 24h)';

  @override
  String get wizardRoleOffline => 'Offline: import a key envelope';

  @override
  String get wizardAppBarCreate => 'Einz Space at Creating';

  @override
  String get wizardAppBarJoin => 'Einz Space at Joining';

  @override
  String get wizardAppBarOffline => 'Import key envelope';

  @override
  String get wizardNext => 'Next';

  @override
  String get wizardBack => 'Back';

  @override
  String get wizardDone => 'Done';

  @override
  String get wizardStepShortEnvelope => 'Envelope';

  @override
  String get wizardTitleName => 'My name';

  @override
  String get wizardTitlePeerName => 'Partner\'s name';

  @override
  String get wizardTitleInvite => 'Invite code';

  @override
  String get wizardTitlePassphrase => 'Passphrase';

  @override
  String get wizardTitlePin => 'Screen lock PIN';

  @override
  String get wizardTitleEnvelope => 'Key envelope';

  @override
  String get wizardTitleIdentity => 'I am';

  @override
  String get wizardEnrollExists =>
      'This server already hosts a space (created by another device). Switch to the Join flow and use the one-time invite code from your partner.';

  @override
  String get wizardEnrollGoJoin => 'Switch to Join flow';

  @override
  String wizardEnrollFailed(String error) {
    return '❌ Registration failed: $error';
  }

  @override
  String get wizardPassphraseHint =>
      'Your partner joins with this passphrase — share it via QR code on the next step.';

  @override
  String get wizardJoinPassphraseHint =>
      'Verify the entry passphrase: enter the exact passphrase the first device created to join';

  @override
  String get wizardJoinPassphraseWrong =>
      'Wrong passphrase: check the exact one the first device created';

  @override
  String get wizardSwitchToEnvelope =>
      'Import sealed key envelope instead (offline)';

  @override
  String get wizardSwitchToPassphrase => 'Use passphrase instead';

  @override
  String get wizardPinHint =>
      'You\'ll enter this PIN at every startup to unlock.';

  @override
  String get welcomeDialogTitleCreate => '🎉 Welcome to your private space';

  @override
  String get welcomeDialogTitleJoin => '🎉 Welcome to the space';

  @override
  String get welcomeDialogMessage =>
      'All set! Messages are end-to-end encrypted and visible only to you two. Start chatting!';

  @override
  String get welcomeDialogStart => 'Start chatting';

  @override
  String setupPageKeyGenFailed(String error) {
    return '❌ Key generation failed: $error';
  }

  @override
  String get setupPageInitFailed => 'Initialization failed, retrying…';

  @override
  String get startupInitFailed =>
      'Startup initialization failed — your data is safe, please retry';

  @override
  String get startupInitRetry => 'Retry';

  @override
  String get setupPagePasteEnvelope => '⚠️ Paste the key envelope (base64)';

  @override
  String get wizardEnvelopeWrong =>
      'Invalid key envelope: make sure the full sealed key copy from the other device is pasted';

  @override
  String get setupPageInviteHint => 'Paste or type the invite code';

  @override
  String get setupPageNeedInvite =>
      '⚠️ Enter the one-time invite code (generated by an authenticated device)';

  @override
  String get wizardInviteWrong =>
      'Invalid invite code: check the code from the first device\'s invite, or ask them to generate a new one';

  @override
  String get setupPageNoEscrow =>
      '❌ No escrow package on the server (set an access passphrase on the other device first)';

  @override
  String setupPageEscrowFailed(String error) {
    return '❌ Passphrase join failed: $error';
  }

  @override
  String get setPinDialogPinLabel => 'PIN (at least 4 characters)';

  @override
  String get setPinDialogPinHint => 'At least 4 digits';

  @override
  String get setPinDialogConfirmLabel => 'Confirm PIN';

  @override
  String get setPinDialogConfirmHint => 'Type it again to confirm';

  @override
  String get setPinDialogSetPin => 'Set PIN';

  @override
  String get setupPageSkipPinTitle => 'Skip app lock?';

  @override
  String get setupPageSkipPinMessage =>
      'Without the app lock the Space Key package won\'t be encrypted on this device; you\'ll need to set it up again after restart. Skip anyway?';

  @override
  String get setPinDialogPinTooShort => 'PIN must be at least 4 characters';

  @override
  String get setPinDialogPinMismatch => 'The two PINs do not match';

  @override
  String setPinDialogSetupFailed(String error) {
    return 'Setup failed: $error';
  }

  @override
  String chatPageLocaleSwitched(String label) {
    return 'Switched to $label';
  }

  @override
  String get chatPageSetLockTitle => 'Set app lock';

  @override
  String get chatPageSetLockClearHint => 'Leave blank and submit to clear PIN';

  @override
  String get chatPageSetLockDone =>
      'App lock set — PIN required at next launch';

  @override
  String get chatPageSetLockConfirmTitle => 'Set app lock?';

  @override
  String get chatPageSetLockConfirmMessage =>
      'Set the app lock? You\'ll need to enter the PIN at every launch.';

  @override
  String get chatPageSetLockCleared =>
      'App lock cleared (enter directly at next launch)';

  @override
  String get chatPageClearLockTitle => 'Clear app lock?';

  @override
  String get chatPageClearLockMessage =>
      'Both PIN fields are empty — clear the app lock? You\'ll enter directly at next launch.';

  @override
  String get chatPageMenuInvite => 'Invite code';

  @override
  String get chatPageTitleBrand => 'EINZ Private Space';

  @override
  String get chatPageMenuChangePassphrase => 'Change passphrase';

  @override
  String get chatPageMenuAvatar => 'Avatar';

  @override
  String get chatPageAvatarUploaded => '✅ Avatar updated';

  @override
  String get chatPageAvatarTooLarge => 'Image too large (max 2MB)';

  @override
  String chatPageAvatarFailed(String error) {
    return 'Avatar upload failed: $error';
  }

  @override
  String get chatPageNameUnset => 'Unset';

  @override
  String get chatPageMenuExit => 'Exit app';

  @override
  String get chatPageRenameNameTitle => 'Change my name';

  @override
  String get chatPageRenameNameLabel => 'New name';

  @override
  String get chatPageRenameDeviceTitle => 'Change device name';

  @override
  String get chatPageRenameDeviceLabel => 'New device name';

  @override
  String chatPageRenameFailed(String error) {
    return 'Rename failed: $error';
  }

  @override
  String get chatPageExitTitle => 'Exit app?';

  @override
  String get chatPageExitMessage =>
      'The app will close completely; you\'ll need your PIN to unlock next time.';

  @override
  String get save => 'Save';

  @override
  String get chatPageChangePassphraseTitle => 'Change passphrase';

  @override
  String get chatPageChangePassphraseOldLabel => 'Current passphrase';

  @override
  String get chatPageChangePassphraseNewLabel => 'New passphrase';

  @override
  String get chatPageChangePassphraseConfirmLabel => 'Confirm new passphrase';

  @override
  String get chatPageChangePassphraseMismatch => 'New passphrases do not match';

  @override
  String get chatPageChangePassphraseConfirmTitle =>
      'Change escrow passphrase?';

  @override
  String get chatPageChangePassphraseConfirmMessage =>
      'Change the escrow passphrase? You\'ll need the new passphrase to decrypt content.';

  @override
  String get chatPageChangePassphraseOldWrong => 'Wrong current passphrase';

  @override
  String get chatPageChangePassphraseNoEscrow =>
      'No passphrase set (nothing to change)';

  @override
  String get chatPageChangePassphraseDone =>
      '✅ Passphrase updated (new devices must use it)';

  @override
  String chatPageChangePassphraseFailed(String error) {
    return 'Failed to change passphrase: $error';
  }

  @override
  String get chatPageEscrowRotatedNotice =>
      'Your partner reset the passphrase — you will be asked for the new one when creating invites or changing it';

  @override
  String get chatPageMenuLocaleLabel => 'Language';

  @override
  String get chatPageMenuBurnLabel => 'Burn-after-read';

  @override
  String get chatPageMenuMyNameLabel => 'My name';

  @override
  String get chatPageMenuDeviceNameLabel => 'Device name';

  @override
  String get chatPagePinLabel => 'PIN';

  @override
  String get chatPagePinSetValue => 'Set';

  @override
  String get chatPagePinUnsetValue => 'Not set';

  @override
  String get chatPageBurnHeading => 'Burn-after (only affects this device)';

  @override
  String get chatPageBurnOff => 'Burn-after is off (messages are kept forever)';

  @override
  String chatPageBurnWillDelete(String duration) {
    return 'Messages will be auto-deleted after $duration';
  }

  @override
  String get chatPageBurnBadge => '⏱ Burn-after';

  @override
  String chatPageSendFailed(String error) {
    return 'Send failed: $error';
  }

  @override
  String chatPageVoiceStartFailed(String error) {
    return 'Recording start failed: $error';
  }

  @override
  String chatPageVoiceFailed(String error) {
    return 'Recording failed: $error';
  }

  @override
  String get chatPageRecordingHint => 'Recording… release to send';

  @override
  String get chatPageInputHint => 'Type a message…';

  @override
  String get chatPageAudioMetaMissing => 'Audio attachment metadata missing';

  @override
  String chatPageAudioPlayFailed(String error) {
    return 'Audio playback failed: $error';
  }

  @override
  String get chatPageAttachPhoto => 'Take photo';

  @override
  String get chatPageAttachGalleryImage => 'Gallery image';

  @override
  String get chatPageAttachVideoCamera => 'Record video';

  @override
  String get chatPageAttachVideoGallery => 'Gallery video';

  @override
  String get chatPageAttachAudioFile => 'Audio file (mp3 etc.)';

  @override
  String get chatPageAttachAnyFile => 'Any file';

  @override
  String get chatPageVideoMetaMissing => 'Video attachment metadata missing';

  @override
  String chatPageVideoPlayFailed(String error) {
    return 'Video playback failed: $error';
  }

  @override
  String chatPageImageLoadFailed(String plaintext) {
    return '$plaintext\n(failed to load)';
  }

  @override
  String get chatPagePlaying => 'Playing…';

  @override
  String get chatPageVoiceLabel => 'Voice';

  @override
  String get chatPageAttachmentMetaMissing => 'Attachment metadata missing';

  @override
  String chatPageSaved(String path) {
    return 'Saved: $path';
  }

  @override
  String chatPageDownloadFailed(String error) {
    return 'Download failed: $error';
  }

  @override
  String get chatPageDeviceRevoked =>
      'Device revoked — local data cleared, please set up again';

  @override
  String get burnOptionUnlimited => 'Unlimited';

  @override
  String get burnOption1Minute => '1 minute';

  @override
  String get burnOption5Minutes => '5 minutes';

  @override
  String get burnOption30Minutes => '30 minutes';

  @override
  String get burnOption1Hour => '1 hour';

  @override
  String get burnOption1Day => '1 day';

  @override
  String get burnOption7Days => '7 days';

  @override
  String get lockPageTitle => 'Einz Locked';

  @override
  String get lockPagePinPrompt => 'Enter PIN to unlock';

  @override
  String lockPageLockedSeconds(int seconds) {
    return 'Locked for $seconds seconds';
  }

  @override
  String get lockPagePinLabel => 'PIN';

  @override
  String get lockPageNoPinSet =>
      'No app lock set (the lock screen only activates when a PIN is set)';

  @override
  String get lockPageUnlock => 'Unlock';

  @override
  String lockPageTooManyAttempts(int seconds) {
    return 'Too many attempts, try again in ${seconds}s';
  }

  @override
  String lockPageUnlockFailed(String error) {
    return 'Unlock failed: $error';
  }
}
